---
- name: Configure Spark Master
  hosts: spark_master
  become: yes
  tasks:
    - name: Test connexion
      ping:

- name: Configure Spark Workers
  hosts: spark_workers
  become: yes
  tasks:
    - name: Test connexion
      ping:

- name: Configure Edge Node
  hosts: spark_edge
  become: yes
  tasks:
    - name: Test connexion
      ping: